Update build-distribute.yml

diff --git a/.github/workflows/build-distribute.yml b/.github/workflows/build-distribute.yml
--- a/.github/workflows/build-distribute.yml
+++ b/.github/workflows/build-distribute.yml
@@ -21,6 +21,22 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        
+      - name: Get version from build.gradle 
+        id: get-version 
+        run: | 
+          VERSION_NAME=$(grep 'versionName' app/build.gradle | sed -E "s/.*versionName ['\"]([0-9.]+)['\"].*/\1/") 
+          echo "version=$VERSION_NAME" >> $GITHUB_ENV 
+        env: 
+          GITHUB_ENV: $GITHUB_ENV
+
+      - name: Verify version 
+        run: | 
+          if [ -z "$VERSION_NAME" ]; then 
+            echo "Version name could not be extracted. Exiting." exit 1 
+          else 
+            echo "Version name is $VERSION_NAME" 
+          fi
 
       - name: Set up JDK
         uses: actions/setup-java@v4
@@ -109,5 +125,12 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: FLW-Mobile-App - APK(s) ${{ inputs.variant }} generated
-          path: app/build/outputs/apk/**/debug/*.apk
+          path: app/build/outputs/apk/**/${{ inputs.build_type }}/*.apk
+      
+      - name: Push to Releases
+        uses: ncipollo/release-action@v1
+        with:
+          artifacts: "app/build/outputs/apk/**/${{ inputs.build_type }}/*.apk"
+          tag: ${{ env.version }}.${{ github.run_number }}
+          token: ${{secrets.GITHUB_TOKEN}}
 
