Update build-distribute.yml

diff --git a/.github/workflows/build-distribute.yml b/.github/workflows/build-distribute.yml
--- a/.github/workflows/build-distribute.yml
+++ b/.github/workflows/build-distribute.yml
@@ -22,22 +22,6 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
         
-      - name: Get version from build.gradle 
-        id: get-version 
-        run: | 
-          VERSION_NAME=$(grep 'versionName' app/build.gradle | sed -E "s/.*versionName ['\"]([0-9.]+)['\"].*/\1/") 
-          echo "version=$VERSION_NAME" >> $GITHUB_ENV 
-        env: 
-          GITHUB_ENV: $GITHUB_ENV
-
-      - name: Verify version 
-        run: | 
-          if [ -z "$VERSION_NAME" ]; then 
-            echo "Version name could not be extracted. Exiting." exit 1 
-          else 
-            echo "Version name is $VERSION_NAME" 
-          fi
-
       - name: Set up JDK
         uses: actions/setup-java@v4
         with:
@@ -88,6 +72,22 @@ jobs:
       - name: Create local.properties
         run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
 
+      - name: Get app version
+        id: get-version 
+        run: | 
+          version=$(bundle exec fastlane get_app_version | grep "App version name" | awk '{print $NF}')
+          echo "version=$VERSION_NAME" >> $GITHUB_ENV 
+        env: 
+          GITHUB_ENV: $GITHUB_ENV
+
+      - name: Verify version 
+        run: | 
+          if [ -z "$VERSION_NAME" ]; then 
+            echo "Version name could not be extracted. Exiting." exit 1 
+          else 
+            echo "Version name is $VERSION_NAME" 
+          fi
+          
       - name: Build and Distribute app to Firebase
         id: build-and-distribute
         run: |
@@ -131,6 +131,6 @@ jobs:
         uses: ncipollo/release-action@v1
         with:
           artifacts: "app/build/outputs/apk/**/${{ inputs.build_type }}/*.apk"
-          tag: ${{ env.version }}.${{ github.run_number }}
+          tag: v${{ env.version }}-${{ inputs.environment }}-${{ github.run_number }}
           token: ${{secrets.GITHUB_TOKEN}}
 
