build environments changed

diff --git a/.github/workflows/build-distribute.yml b/.github/workflows/build-distribute.yml
--- a/.github/workflows/build-distribute.yml
+++ b/.github/workflows/build-distribute.yml
@@ -68,9 +68,9 @@ jobs:
 
       - name: Capitalize first letter of variant
         run: echo "capitalizedVariant=$(echo '${{ inputs.variant }}' | awk '{print toupper(substr($0,1,1)) substr($0,2)}')" >> $GITHUB_ENV
+
       - name: Decode Firebase Credentials
         run: |
-          
           case "$capitalizedVariant" in
             SakshamStag|SakshamUat|Saksham)
               echo "${{ secrets.FIREBASE_CREDENTIALS_JSON_SAKSHAM_ASSAM }}" | base64 --decode > firebase_credentials.json
@@ -82,12 +82,12 @@ jobs:
               echo "${{ secrets.FIREBASE_CREDENTIALS_JSON_UTPRERONA_XUSHRUKHA }}" | base64 --decode > firebase_credentials.json
               ;;
             *)
-              echo "Unknown variant: $variant"
+              echo "Unknown variant: $capitalizedVariant"
               exit 1
               ;;
           esac
       
-
+      
 
       - name: Decode Google Play JSON key
         if: ${{ inputs.build_type == 'release' }}
@@ -97,7 +97,7 @@ jobs:
       - name: Decode keystore
         run: |
           echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ${{ github.workspace }}/keystore.jks
-          echo "Keystore path: ${{ github.workspace }}/keystore.jks"
+      
 
       - name: Create local.properties
         run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
@@ -110,17 +110,31 @@ jobs:
         env:
           GITHUB_ENV: $GITHUB_ENV
 
-      - name: Verify version
-        run: |
-          if [ -z "$VERSION_NAME" ]; then 
-            echo "Version name could not be extracted. Exiting." exit 1 
-          else 
-            echo "Version name is $VERSION_NAME" 
-          fi
-
       - name: Build and Distribute app to Firebase
         id: build-and-distribute
         run: |
+          
+          # Validate required secrets
+          required_secrets=(
+            "ENCRYPTED_PASS_KEY"
+            "ABHA_CLIENT_ID"
+            "ABHA_CLIENT_SECRET"
+            "BASE_TMC_URL"
+            "BASE_ABHA_URL"
+            "ABHA_TOKEN_URL"
+            "ABHA_AUTH_URL"
+            "CHAT_URL"
+            "KEYSTORE_PASSWORD"
+            "KEY_ALIAS"
+            "KEY_PASSWORD"
+            "FIREBASE_APP_ID"
+          )
+          for secret in "${required_secrets[@]}"; do
+            if [ -z "${!secret}" ]; then
+            echo "Error: Required secret $secret is not set"
+              exit 1
+            fi
+          done
 
           # Set app URLs used in the codebase
           export ENCRYPTED_PASS_KEY=${{ secrets.ENCRYPTED_PASS_KEY }}
